<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['imap_app_description'] = 'IMAP и POP сервер предоставляет стандартный набор услуг для почтовых клиентов (Thunderbird, Mail, Evolution, Outlook/Express и т.п.), чтобы подключиться к серверу и получить письма.';
$lang['imap_app_name'] = 'IMAP и POP Сервер';
$lang['imap_imap'] = 'IMAP';
$lang['imap_imaps'] = 'Безопасный IMAP';
$lang['imap_mail_service_invalid'] = 'Почтовая служба - инвалид.';
$lang['imap_pop3'] = 'POP';
$lang['imap_pop3s'] = 'Безопасный POP';
$lang['imap_push_email'] = 'Push E-mail';
