<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['imap_app_description'] = 'Serwer IMAP oraz POP dostarcza standardowe usługi pocztowe dla klientów pocztowych (np. Thinderbird, Poczta Systemu Windows, Evolution, Outlook/Express, itd.) w celu pobrania i wyświetlenia wiadomości email.';
$lang['imap_app_name'] = 'Serwer IMAP i POP';
$lang['imap_imap'] = 'IMAP';
$lang['imap_imaps'] = 'Bezpieczny IMAP';
$lang['imap_mail_service_invalid'] = 'Usługa pocztowa jest nieprawidłowa.';
$lang['imap_pop3'] = 'POP';
$lang['imap_pop3s'] = 'Bezpieczny POP';
$lang['imap_push_email'] = 'Push E-mail';
